services:

  mysql:
    image: ghcr.io/php-not-dead/mysql:${MYSQL_VERSION}
    container_name: ${DOCKER_GROUP}_mysql
    user: ${UID:-1000}
    restart: always
    volumes:
      - ./.build/mysql/my.cnf:/etc/my.cnf:ro
      - ./.build/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - mysql:/var/lib/mysql
    ports:
      - 127.0.0.1:${DB_DOCKER_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - ${DOCKER_GROUP}

  redis:
    container_name: ${DOCKER_GROUP}_redis
    image: ghcr.io/php-not-dead/redis:8.2.1
    restart: on-failure
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - redis:/data
    networks:
      - ${DOCKER_GROUP}

  rabbitmq:
    image: ghcr.io/php-not-dead/rabbitmq:${RABBITMQ_VERSION}
    volumes:
      - .rabbitmq:/var/lib/rabbitmq
      - ./.build/rabbitmq/plugins/rabbitmq_delayed_message_exchange-4.1.0.ez:/plugins/rabbitmq_delayed_message_exchange-4.1.0.ez
      - ./.build/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./.build/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./.build/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    ports:
      - 127.0.0.1:${RABBITMQ_PORT:-5672}:5672
      - 127.0.0.1:${RABBITMQ_MANAGER_PORT:-15672}:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-guest}
    container_name: ${DOCKER_GROUP}_rabbitmq
    networks:
      - ${DOCKER_GROUP}

volumes:
  mysql:
  redis:
  rabbitmq:

networks:
  php_not_dead:
    name: ${DOCKER_GROUP}
    driver: bridge
    external: true
